### ISSUE TITLE
petrol api

### ISSUE THREAD

**Issue by matjaz** [lovromazgon/kam-tankat#5]
http://www.petrol.si/api/fuel_prices.json vraca 403. je kje kak drug data api? mogoce ves kaj? hvala.

**Comment by lovromazgon** [comment]
Uf, odkar sem aplikacijo razvil se nisem več s tem ukvarjal, tako da bi težko pomagal. Mogoče se pa najde kak drug API, sicer pa bo treba parsat iz kakšnega drugega vira - npr. http://poraba.com zgleda da redno aktualizirajo.

**Comment by lovromazgon** [comment]
Evo, sej sem našel, na tej strani so objavili celo dva linka za cene goriv, eden za XML in drugi za JSON.

http://www.petrol.si/povej/ali-je-mozno-dobivati-podatke-o-cenah-goriv-v-xml-ali-kaki-drugi-obliki-za-nadaljno-obdelavo

**Comment by matjaz** [comment]
10x http://www.petrol.eu/api/fuel_prices.json

**Comment by matjaz** [comment]
aha, lahk se uporabi https://crossorigin.me

**Comment by lovromazgon** [comment]
Za slovenski API se to res lahko uporabi, problem je pa za avstrijskega, ki uporablja POST request, kjer pa ta rešitev ne deluje.

**Comment by lovromazgon** [comment]
No zdaj sem si pa vzel malo časa in popravil aplikacijo, tako da spet deluje. Za slovenski API sem uporabil crossorigin.me, za avstrijskega pa menjal hosting PHP scripte. LP! :)

**Comment by matjaz** [comment]
hvala. saj za hosting ni problem. sem postavil na heroku https://kam-tankat.herokuapp.com
